version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    network_mode: host
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CREATE_TOPICS: "group:1:1,user:1:1,sms:1:1,push:1:1"
    network_mode: host

  gateway-server:
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
    container_name: gateway-server
    network_mode: host
  
  group-notifier:
    build:
      context: ./
      dockerfile: ./group-notifier/Dockerfile
    container_name: group-notifier
    network_mode: host

  user-notifier:
    build:
      context: ./
      dockerfile: ./user-notifier/Dockerfile
    container_name: user-notifier
    network_mode: host
  
  notifications-forwarder:
    build:
      context: ./
      dockerfile: ./notifications-forwarder/Dockerfile
    container_name: notifications-forwarder
    network_mode: host
  
  redis:
    image: 'bitnami/redis:5.0.9'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    network_mode: host

  rate-limiter:
    build:
      context: ./
      dockerfile: ./rate-limiter/Dockerfile
    container_name: rate-limiter
    network_mode: host

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    volumes:
      - ./swagger_gateway_specs.json:/swagger_gateway_specs.json
    environment:
      SWAGGER_JSON: /swagger_gateway_specs.json
    network_mode: host