version: '3.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    network_mode: host
  kafka:
    image: wurstmeister/kafka:2.12-2.5.0
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      KAFKA_CREATE_TOPICS: "group:1:1,user:1:1,sms:1:1,push:1:1"
    network_mode: host